# Generated by Django 5.2 on 2025-04-21 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atelier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Etape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('consignes', models.TextField(blank=True)),
                ('ordre', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RetourExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FicheSuivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('atelier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.atelier')),
                ('controleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_controleur', to=settings.AUTH_USER_MODEL)),
                ('operateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_operateur', to=settings.AUTH_USER_MODEL)),
                ('incidents', models.ManyToManyField(blank=True, to='checklist.incident')),
                ('retour_experience', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checklist.retourexperience')),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_pause', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('validation', models.CharField(choices=[('conforme', 'Conforme'), ('non_conforme', 'Non conforme'), ('en_attente', 'En attente')], default='en_attente', max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('duree', models.DurationField(blank=True, null=True)),
                ('signature_operateur', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('signature_controleur', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.etape')),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='checklist.fichesuivi')),
            ],
        ),
    ]
