# Generated by Django 5.2 on 2025-04-21 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fichesuivi',
            name='date_validation_controleur',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichesuivi',
            name='date_validation_operateur',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichesuivi',
            name='valide_par_controleur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_validees_controleur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fichesuivi',
            name='valide_par_operateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_validees_operateur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tache',
            name='date_validation_controleur',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tache',
            name='date_validation_operateur',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tache',
            name='valide_par_controleur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_validees_controleur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tache',
            name='valide_par_operateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_validees_operateur', to=settings.AUTH_USER_MODEL),
        ),
    ]
