# Generated by Django 5.2 on 2025-04-21 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_fichesuivi_date_validation_controleur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MelangeMortier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaires', models.TextField(blank=True)),
                ('densite', models.FloatField(blank=True, null=True)),
                ('date_saisie', models.DateTimeField(auto_now=True)),
                ('fiche', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='melange_mortier', to='checklist.fichesuivi')),
            ],
        ),
        migrations.CreateModel(
            name='MesureComposants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciment', models.FloatField(blank=True, null=True)),
                ('sable', models.FloatField(blank=True, null=True)),
                ('agent_moussant', models.FloatField(blank=True, null=True)),
                ('fibre_verre', models.FloatField(blank=True, null=True)),
                ('dsp_xl', models.FloatField(blank=True, null=True)),
                ('hdr', models.FloatField(blank=True, null=True)),
                ('eau', models.FloatField(blank=True, null=True)),
                ('commentaires', models.TextField(blank=True)),
                ('date_saisie', models.DateTimeField(auto_now=True)),
                ('fiche', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mesure_composants', to='checklist.fichesuivi')),
            ],
        ),
    ]
