# Generated by Django 5.2 on 2025-04-21 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_melangemortier_mesurecomposants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='melangemortier',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='melangemortier',
            name='valide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='melangemortier',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='melanges_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mesurecomposants',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mesurecomposants',
            name='valide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mesurecomposants',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesures_validees', to=settings.AUTH_USER_MODEL),
        ),
    ]
