# Generated by Django 5.2 on 2025-04-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0004_melangemortier_date_validation_melangemortier_valide_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='melangemortier',
            name='date_debut',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='melangemortier',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='melangemortier',
            name='date_pause',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='melangemortier',
            name='duree',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mesurecomposants',
            name='date_debut',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mesurecomposants',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mesurecomposants',
            name='date_pause',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mesurecomposants',
            name='duree',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
