# Generated by Django 5.2 on 2025-04-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0005_melangemortier_date_debut_melangemortier_date_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='melangemortier',
            name='etape_ajouter_fibre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='melangemortier',
            name='etape_ajuster_eau',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='melangemortier',
            name='etape_melanger_1min',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='melangemortier',
            name='etape_mesurer_densite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='melangemortier',
            name='etape_verser_ciment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='melangemortier',
            name='etape_verser_eau',
            field=models.BooleanField(default=False),
        ),
    ]
